/*
 * Accounting API
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * API version: 2.2.8
 * Contact: api@xero.com
 * Generated by: OpenAPI Generator (https://openapi-generator.tech)
 */

package openapi
// LineAmountTypes Line amounts are exclusive of tax by default if you don’t specify this element. See Line Amount Types
type LineAmountTypes string

// List of LineAmountTypes
const (
	LINEAMOUNTTYPES_EXCLUSIVE LineAmountTypes = "Exclusive"
	LINEAMOUNTTYPES_INCLUSIVE LineAmountTypes = "Inclusive"
	LINEAMOUNTTYPES_NO_TAX LineAmountTypes = "NoTax"
)
