/*
 * Accounting API
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * API version: 2.2.8
 * Contact: api@xero.com
 * Generated by: OpenAPI Generator (https://openapi-generator.tech)
 */

package openapi
import (
	"time"
)
// CreditNote struct for CreditNote
type CreditNote struct {
	// See Credit Note Types
	Type string `json:"Type,omitempty"`
	Contact Contact `json:"Contact,omitempty"`
	// The date the credit note is issued YYYY-MM-DD. If the Date element is not specified then it will default to the current date based on the timezone setting of the organisation
	Date string `json:"Date,omitempty"`
	// See Credit Note Status Codes
	Status string `json:"Status,omitempty"`
	LineAmountTypes LineAmountTypes `json:"LineAmountTypes,omitempty"`
	// See Invoice Line Items
	LineItems []LineItem `json:"LineItems,omitempty"`
	// The subtotal of the credit note excluding taxes
	SubTotal float64 `json:"SubTotal,omitempty"`
	// The total tax on the credit note
	TotalTax float64 `json:"TotalTax,omitempty"`
	// The total of the Credit Note(subtotal + total tax)
	Total float64 `json:"Total,omitempty"`
	// UTC timestamp of last update to the credit note
	UpdatedDateUTC time.Time `json:"UpdatedDateUTC,omitempty"`
	CurrencyCode CurrencyCode `json:"CurrencyCode,omitempty"`
	// Date when credit note was fully paid(UTC format)
	FullyPaidOnDate string `json:"FullyPaidOnDate,omitempty"`
	// Xero generated unique identifier
	CreditNoteID string `json:"CreditNoteID,omitempty"`
	// ACCRECCREDIT – Unique alpha numeric code identifying credit note (when missing will auto-generate from your Organisation Invoice Settings)
	CreditNoteNumber string `json:"CreditNoteNumber,omitempty"`
	// ACCRECCREDIT only – additional reference number
	Reference string `json:"Reference,omitempty"`
	// boolean to indicate if a credit note has been sent to a contact via  the Xero app (currently read only)
	SentToContact bool `json:"SentToContact,omitempty"`
	// The currency rate for a multicurrency invoice. If no rate is specified, the XE.com day rate is used
	CurrencyRate float64 `json:"CurrencyRate,omitempty"`
	// The remaining credit balance on the Credit Note
	RemainingCredit float64 `json:"RemainingCredit,omitempty"`
	// See Allocations
	Allocations []Allocation `json:"Allocations,omitempty"`
	// The amount of applied to an invoice
	AppliedAmount float64 `json:"AppliedAmount,omitempty"`
	// See Payments
	Payments []Payment `json:"Payments,omitempty"`
	// See BrandingThemes
	BrandingThemeID string `json:"BrandingThemeID,omitempty"`
	// A string to indicate if a invoice status
	StatusAttributeString string `json:"StatusAttributeString,omitempty"`
	// boolean to indicate if a credit note has an attachment
	HasAttachments bool `json:"HasAttachments,omitempty"`
	// A boolean to indicate if a credit note has an validation errors
	HasErrors bool `json:"HasErrors,omitempty"`
	// Displays array of validation error messages from the API
	ValidationErrors []ValidationError `json:"ValidationErrors,omitempty"`
}
