/*
 * Accounting API
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * API version: 2.2.8
 * Contact: api@xero.com
 * Generated by: OpenAPI Generator (https://openapi-generator.tech)
 */

package openapi
import (
	"time"
)
// Quote struct for Quote
type Quote struct {
	// QuoteID GUID is automatically generated and is returned after create or GET.
	QuoteID string `json:"QuoteID,omitempty"`
	// Unique alpha numeric code identifying a quote (Max Length = 255)
	QuoteNumber string `json:"QuoteNumber,omitempty"`
	// Additional reference number
	Reference string `json:"Reference,omitempty"`
	// Terms of the quote
	Terms string `json:"Terms,omitempty"`
	Contact Contact `json:"Contact,omitempty"`
	// See LineItems
	LineItems []LineItem `json:"LineItems,omitempty"`
	// Date quote was issued – YYYY-MM-DD. If the Date element is not specified it will default to the current date based on the timezone setting of the organisation
	Date string `json:"Date,omitempty"`
	// Date the quote was issued (YYYY-MM-DD)
	DateString string `json:"DateString,omitempty"`
	// Date the quote expires – YYYY-MM-DD.
	ExpiryDate string `json:"ExpiryDate,omitempty"`
	// Date the quote expires – YYYY-MM-DD.
	ExpiryDateString string `json:"ExpiryDateString,omitempty"`
	Status QuoteStatusCodes `json:"Status,omitempty"`
	CurrencyCode CurrencyCode `json:"CurrencyCode,omitempty"`
	// The currency rate for a multicurrency quote
	CurrencyRate float64 `json:"CurrencyRate,omitempty"`
	// Total of quote excluding taxes.
	SubTotal float64 `json:"SubTotal,omitempty"`
	// Total tax on quote
	TotalTax float64 `json:"TotalTax,omitempty"`
	// Total of Quote tax inclusive (i.e. SubTotal + TotalTax). This will be ignored if it doesn’t equal the sum of the LineAmounts
	Total float64 `json:"Total,omitempty"`
	// Total of discounts applied on the quote line items
	TotalDiscount float64 `json:"TotalDiscount,omitempty"`
	// Title text for the quote
	Title string `json:"Title,omitempty"`
	// Summary text for the quote
	Summary string `json:"Summary,omitempty"`
	// See BrandingThemes
	BrandingThemeID string `json:"BrandingThemeID,omitempty"`
	// Last modified date UTC format
	UpdatedDateUTC time.Time `json:"UpdatedDateUTC,omitempty"`
	LineAmountTypes QuoteLineAmountTypes `json:"LineAmountTypes,omitempty"`
	// A string to indicate if a invoice status
	StatusAttributeString string `json:"StatusAttributeString,omitempty"`
	// Displays array of validation error messages from the API
	ValidationErrors []ValidationError `json:"ValidationErrors,omitempty"`
}
