/*
 * Accounting API
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * API version: 2.2.8
 * Contact: api@xero.com
 * Generated by: OpenAPI Generator (https://openapi-generator.tech)
 */

package openapi
import (
	"time"
)
// Account struct for Account
type Account struct {
	// Customer defined alpha numeric account code e.g 200 or SALES (max length = 10)
	Code string `json:"Code,omitempty"`
	// Name of account (max length = 150)
	Name string `json:"Name,omitempty"`
	// The Xero identifier for an account – specified as a string following  the endpoint name   e.g. /297c2dc5-cc47-4afd-8ec8-74990b8761e9
	AccountID string `json:"AccountID,omitempty"`
	Type AccountType `json:"Type,omitempty"`
	// For bank accounts only (Account Type BANK)
	BankAccountNumber string `json:"BankAccountNumber,omitempty"`
	// Accounts with a status of ACTIVE can be updated to ARCHIVED. See Account Status Codes
	Status string `json:"Status,omitempty"`
	// Description of the Account. Valid for all types of accounts except bank accounts (max length = 4000)
	Description string `json:"Description,omitempty"`
	// For bank accounts only. See Bank Account types
	BankAccountType string `json:"BankAccountType,omitempty"`
	CurrencyCode CurrencyCode `json:"CurrencyCode,omitempty"`
	// The tax type from TaxRates
	TaxType string `json:"TaxType,omitempty"`
	// Boolean – describes whether account can have payments applied to it
	EnablePaymentsToAccount bool `json:"EnablePaymentsToAccount,omitempty"`
	// Boolean – describes whether account code is available for use with expense claims
	ShowInExpenseClaims bool `json:"ShowInExpenseClaims,omitempty"`
	// See Account Class Types
	Class string `json:"Class,omitempty"`
	// If this is a system account then this element is returned. See System Account types. Note that non-system accounts may have this element set as either “” or null.
	SystemAccount string `json:"SystemAccount,omitempty"`
	// Shown if set
	ReportingCode string `json:"ReportingCode,omitempty"`
	// Shown if set
	ReportingCodeName string `json:"ReportingCodeName,omitempty"`
	// boolean to indicate if an account has an attachment (read only)
	HasAttachments bool `json:"HasAttachments,omitempty"`
	// Last modified date UTC format
	UpdatedDateUTC time.Time `json:"UpdatedDateUTC,omitempty"`
	// Boolean – describes whether the account is shown in the watchlist widget on the dashboard
	AddToWatchlist bool `json:"AddToWatchlist,omitempty"`
	// Displays array of validation error messages from the API
	ValidationErrors []ValidationError `json:"ValidationErrors,omitempty"`
}
