/*
 * Accounting API
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * API version: 2.2.8
 * Contact: api@xero.com
 * Generated by: OpenAPI Generator (https://openapi-generator.tech)
 */

package openapi
// TenNinteyNineContact struct for TenNinteyNineContact
type TenNinteyNineContact struct {
	// Box 1 on 1099 Form
	Box1 float64 `json:"Box1,omitempty"`
	// Box 2 on 1099 Form
	Box2 float64 `json:"Box2,omitempty"`
	// Box 3 on 1099 Form
	Box3 float64 `json:"Box3,omitempty"`
	// Box 4 on 1099 Form
	Box4 float64 `json:"Box4,omitempty"`
	// Box 5 on 1099 Form
	Box5 float64 `json:"Box5,omitempty"`
	// Box 6 on 1099 Form
	Box6 float64 `json:"Box6,omitempty"`
	// Box 7 on 1099 Form
	Box7 float64 `json:"Box7,omitempty"`
	// Box 8 on 1099 Form
	Box8 float64 `json:"Box8,omitempty"`
	// Box 9 on 1099 Form
	Box9 float64 `json:"Box9,omitempty"`
	// Box 10 on 1099 Form
	Box10 float64 `json:"Box10,omitempty"`
	// Box 11 on 1099 Form
	Box11 float64 `json:"Box11,omitempty"`
	// Box 13 on 1099 Form
	Box13 float64 `json:"Box13,omitempty"`
	// Box 14 on 1099 Form
	Box14 float64 `json:"Box14,omitempty"`
	// Contact name on 1099 Form
	Name string `json:"Name,omitempty"`
	// Contact Fed Tax ID type
	FederalTaxIDType string `json:"FederalTaxIDType,omitempty"`
	// Contact city on 1099 Form
	City string `json:"City,omitempty"`
	// Contact zip on 1099 Form
	Zip string `json:"Zip,omitempty"`
	// Contact State on 1099 Form
	State string `json:"State,omitempty"`
	// Contact email on 1099 Form
	Email string `json:"Email,omitempty"`
	// Contact address on 1099 Form
	StreetAddress string `json:"StreetAddress,omitempty"`
	// Contact tax id on 1099 Form
	TaxID string `json:"TaxID,omitempty"`
	// Contact contact id
	ContactId string `json:"ContactId,omitempty"`
}
