/*
 * Accounting API
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * API version: 2.2.8
 * Contact: api@xero.com
 * Generated by: OpenAPI Generator (https://openapi-generator.tech)
 */

package openapi
import (
	"time"
)
// BatchPayment struct for BatchPayment
type BatchPayment struct {
	Account Account `json:"Account,omitempty"`
	// (NZ Only) Optional references for the batch payment transaction. It will also show with the batch payment transaction in the bank reconciliation Find & Match screen. Depending on your individual bank, the detail may also show on the bank statement you import into Xero.
	Reference string `json:"Reference,omitempty"`
	// (NZ Only) Optional references for the batch payment transaction. It will also show with the batch payment transaction in the bank reconciliation Find & Match screen. Depending on your individual bank, the detail may also show on the bank statement you import into Xero.
	Particulars string `json:"Particulars,omitempty"`
	// (NZ Only) Optional references for the batch payment transaction. It will also show with the batch payment transaction in the bank reconciliation Find & Match screen. Depending on your individual bank, the detail may also show on the bank statement you import into Xero.
	Code string `json:"Code,omitempty"`
	// (Non-NZ Only) These details are sent to the org’s bank as a reference for the batch payment transaction. They will also show with the batch payment transaction in the bank reconciliation Find & Match screen. Depending on your individual bank, the detail may also show on the bank statement imported into Xero. Maximum field length = 18
	Details string `json:"Details,omitempty"`
	// (UK Only) Only shows on the statement line in Xero. Max length =18
	Narrative string `json:"Narrative,omitempty"`
	// The Xero generated unique identifier for the bank transaction (read-only)
	BatchPaymentID string `json:"BatchPaymentID,omitempty"`
	// Date the payment is being made (YYYY-MM-DD) e.g. 2009-09-06
	DateString string `json:"DateString,omitempty"`
	// Date the payment is being made (YYYY-MM-DD) e.g. 2009-09-06
	Date string `json:"Date,omitempty"`
	// The amount of the payment. Must be less than or equal to the outstanding amount owing on the invoice e.g. 200.00
	Amount float64 `json:"Amount,omitempty"`
	Payments []Payment `json:"Payments,omitempty"`
	// PAYBATCH for bill payments or RECBATCH for sales invoice payments (read-only)
	Type string `json:"Type,omitempty"`
	// AUTHORISED or DELETED (read-only). New batch payments will have a status of AUTHORISED. It is not possible to delete batch payments via the API.
	Status string `json:"Status,omitempty"`
	// The total of the payments that make up the batch (read-only)
	TotalAmount string `json:"TotalAmount,omitempty"`
	// UTC timestamp of last update to the payment
	UpdatedDateUTC time.Time `json:"UpdatedDateUTC,omitempty"`
	// Booelan that tells you if the batch payment has been reconciled (read-only)
	IsReconciled string `json:"IsReconciled,omitempty"`
}
