/*
 * Accounting API
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * API version: 2.2.8
 * Contact: api@xero.com
 * Generated by: OpenAPI Generator (https://openapi-generator.tech)
 */

package openapi
// JournalLine struct for JournalLine
type JournalLine struct {
	// Xero identifier for Journal
	JournalLineID string `json:"JournalLineID,omitempty"`
	// See Accounts
	AccountID string `json:"AccountID,omitempty"`
	// See Accounts
	AccountCode string `json:"AccountCode,omitempty"`
	AccountType AccountType `json:"AccountType,omitempty"`
	// See AccountCodes
	AccountName string `json:"AccountName,omitempty"`
	// The description from the source transaction line item. Only returned if populated.
	Description string `json:"Description,omitempty"`
	// Net amount of journal line. This will be a positive value for a debit and negative for a credit
	NetAmount float64 `json:"NetAmount,omitempty"`
	// Gross amount of journal line (NetAmount + TaxAmount).
	GrossAmount float64 `json:"GrossAmount,omitempty"`
	// Total tax on a journal line
	TaxAmount float64 `json:"TaxAmount,omitempty"`
	// The tax type from TaxRates
	TaxType string `json:"TaxType,omitempty"`
	// see TaxRates
	TaxName string `json:"TaxName,omitempty"`
	// Optional Tracking Category – see Tracking. Any JournalLine can have a maximum of 2 <TrackingCategory> elements.
	TrackingCategories []TrackingCategory `json:"TrackingCategories,omitempty"`
}
