/*
 * Accounting API
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * API version: 2.2.8
 * Contact: api@xero.com
 * Generated by: OpenAPI Generator (https://openapi-generator.tech)
 */

package openapi
// ReportFields struct for ReportFields
type ReportFields struct {
	FieldID string `json:"FieldID,omitempty"`
	Description string `json:"Description,omitempty"`
	Value string `json:"Value,omitempty"`
}
