/*
 * Accounting API
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * API version: 2.2.8
 * Contact: api@xero.com
 * Generated by: OpenAPI Generator (https://openapi-generator.tech)
 */

package openapi
// Attachment struct for Attachment
type Attachment struct {
	// Unique ID for the file
	AttachmentID string `json:"AttachmentID,omitempty"`
	// Name of the file
	FileName string `json:"FileName,omitempty"`
	// URL to the file on xero.com
	Url string `json:"Url,omitempty"`
	// Type of file
	MimeType string `json:"MimeType,omitempty"`
	// Length of the file content
	ContentLength float32 `json:"ContentLength,omitempty"`
	// Include the file with the online invoice
	IncludeOnline bool `json:"IncludeOnline,omitempty"`
}
