/*
 * Accounting API
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * API version: 2.2.8
 * Contact: api@xero.com
 * Generated by: OpenAPI Generator (https://openapi-generator.tech)
 */

package openapi
// QuoteStatusCodes The status of the quote.
type QuoteStatusCodes string

// List of QuoteStatusCodes
const (
	QUOTESTATUSCODES_DRAFT QuoteStatusCodes = "DRAFT"
	QUOTESTATUSCODES_SENT QuoteStatusCodes = "SENT"
	QUOTESTATUSCODES_DECLINED QuoteStatusCodes = "DECLINED"
	QUOTESTATUSCODES_ACCEPTED QuoteStatusCodes = "ACCEPTED"
	QUOTESTATUSCODES_INVOICED QuoteStatusCodes = "INVOICED"
)
