/*
 * Accounting API
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * API version: 2.2.8
 * Contact: api@xero.com
 * Generated by: OpenAPI Generator (https://openapi-generator.tech)
 */

package openapi
// BatchPaymentDetails Bank details for use on a batch payment stored with each contact
type BatchPaymentDetails struct {
	// Bank account number for use with Batch Payments
	BankAccountNumber string `json:"BankAccountNumber,omitempty"`
	// Name of bank for use with Batch Payments
	BankAccountName string `json:"BankAccountName,omitempty"`
	// (Non-NZ Only) These details are sent to the org’s bank as a reference for the batch payment transaction. They will also show with the batch payment transaction in the bank reconciliation Find & Match screen. Depending on your individual bank, the detail may also show on the bank statement imported into Xero. Maximum field length = 18
	Details string `json:"Details,omitempty"`
	// (NZ Only) Optional references for the batch payment transaction. It will also show with the batch payment transaction in the bank reconciliation Find & Match screen. Depending on your individual bank, the detail may also show on the bank statement you import into Xero.
	Code string `json:"Code,omitempty"`
	// (NZ Only) Optional references for the batch payment transaction. It will also show with the batch payment transaction in the bank reconciliation Find & Match screen. Depending on your individual bank, the detail may also show on the bank statement you import into Xero.
	Reference string `json:"Reference,omitempty"`
}
