/*
 * Accounting API
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * API version: 2.2.8
 * Contact: api@xero.com
 * Generated by: OpenAPI Generator (https://openapi-generator.tech)
 */

package openapi
// ReportRows struct for ReportRows
type ReportRows struct {
	RowType RowType `json:"RowType,omitempty"`
	Title string `json:"Title,omitempty"`
	Cells []ReportCell `json:"Cells,omitempty"`
	Rows []ReportRow `json:"Rows,omitempty"`
}
