/*
 * Accounting API
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * API version: 2.2.8
 * Contact: api@xero.com
 * Generated by: OpenAPI Generator (https://openapi-generator.tech)
 */

package openapi
// ExternalLink struct for ExternalLink
type ExternalLink struct {
	// See External link types
	LinkType string `json:"LinkType,omitempty"`
	// URL for service e.g. http://twitter.com/xeroapi
	Url string `json:"Url,omitempty"`
	Description string `json:"Description,omitempty"`
}
