/*
 * Accounting API
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * API version: 2.2.8
 * Contact: api@xero.com
 * Generated by: OpenAPI Generator (https://openapi-generator.tech)
 */

package openapi
import (
	"time"
)
// BankTransfer struct for BankTransfer
type BankTransfer struct {
	FromBankAccount Account `json:"FromBankAccount"`
	ToBankAccount Account `json:"ToBankAccount"`
	// amount of the transaction
	Amount float64 `json:"Amount"`
	// The date of the Transfer YYYY-MM-DD
	Date string `json:"Date,omitempty"`
	// The identifier of the Bank Transfer
	BankTransferID string `json:"BankTransferID,omitempty"`
	// The currency rate
	CurrencyRate float64 `json:"CurrencyRate,omitempty"`
	// The Bank Transaction ID for the source account
	FromBankTransactionID string `json:"FromBankTransactionID,omitempty"`
	// The Bank Transaction ID for the destination account
	ToBankTransactionID string `json:"ToBankTransactionID,omitempty"`
	// Boolean to indicate if a Bank Transfer has an attachment
	HasAttachments bool `json:"HasAttachments,omitempty"`
	// UTC timestamp of creation date of bank transfer
	CreatedDateUTC time.Time `json:"CreatedDateUTC,omitempty"`
	// Displays array of validation error messages from the API
	ValidationErrors []ValidationError `json:"ValidationErrors,omitempty"`
}
