/*
 * Accounting API
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * API version: 2.2.8
 * Contact: api@xero.com
 * Generated by: OpenAPI Generator (https://openapi-generator.tech)
 */

package openapi
// TaxComponent struct for TaxComponent
type TaxComponent struct {
	// Name of Tax Component
	Name string `json:"Name,omitempty"`
	// Tax Rate (up to 4dp)
	Rate float64 `json:"Rate,omitempty"`
	// Boolean to describe if Tax rate is compounded.
	IsCompound bool `json:"IsCompound,omitempty"`
	// Boolean to describe if tax rate is non-recoverable. Non-recoverable rates are only applicable to Canadian organisations
	IsNonRecoverable bool `json:"IsNonRecoverable,omitempty"`
}
