/*
 * Accounting API
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * API version: 2.2.8
 * Contact: api@xero.com
 * Generated by: OpenAPI Generator (https://openapi-generator.tech)
 */

package openapi
// RowType the model 'RowType'
type RowType string

// List of RowType
const (
	ROWTYPE_HEADER RowType = "Header"
	ROWTYPE_SECTION RowType = "Section"
	ROWTYPE_ROW RowType = "Row"
	ROWTYPE_SUMMARY_ROW RowType = "SummaryRow"
)
