/*
 * Accounting API
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * API version: 2.2.8
 * Contact: api@xero.com
 * Generated by: OpenAPI Generator (https://openapi-generator.tech)
 */

package openapi
// PaymentTermType the model 'PaymentTermType'
type PaymentTermType string

// List of PaymentTermType
const (
	PAYMENTTERMTYPE_DAYSAFTERBILLDATE PaymentTermType = "DAYSAFTERBILLDATE"
	PAYMENTTERMTYPE_DAYSAFTERBILLMONTH PaymentTermType = "DAYSAFTERBILLMONTH"
	PAYMENTTERMTYPE_OFCURRENTMONTH PaymentTermType = "OFCURRENTMONTH"
	PAYMENTTERMTYPE_OFFOLLOWINGMONTH PaymentTermType = "OFFOLLOWINGMONTH"
)
