/*
 * Accounting API
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * API version: 2.2.8
 * Contact: api@xero.com
 * Generated by: OpenAPI Generator (https://openapi-generator.tech)
 */

package openapi
import (
	"time"
)
// ExpenseClaim struct for ExpenseClaim
type ExpenseClaim struct {
	// Xero generated unique identifier for an expense claim
	ExpenseClaimID string `json:"ExpenseClaimID,omitempty"`
	// Current status of an expense claim – see status types
	Status string `json:"Status,omitempty"`
	// See Payments
	Payments []Payment `json:"Payments,omitempty"`
	User User `json:"User,omitempty"`
	Receipts []Receipt `json:"Receipts,omitempty"`
	// Last modified date UTC format
	UpdatedDateUTC time.Time `json:"UpdatedDateUTC,omitempty"`
	// The total of an expense claim being paid
	Total float64 `json:"Total,omitempty"`
	// The amount due to be paid for an expense claim
	AmountDue float64 `json:"AmountDue,omitempty"`
	// The amount still to pay for an expense claim
	AmountPaid float64 `json:"AmountPaid,omitempty"`
	// The date when the expense claim is due to be paid YYYY-MM-DD
	PaymentDueDate string `json:"PaymentDueDate,omitempty"`
	// The date the expense claim will be reported in Xero YYYY-MM-DD
	ReportingDate string `json:"ReportingDate,omitempty"`
	// The Xero identifier for the Receipt e.g.  e59a2c7f-1306-4078-a0f3-73537afcbba9
	ReceiptID string `json:"ReceiptID,omitempty"`
}
