/*
 * Accounting API
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * API version: 2.2.8
 * Contact: api@xero.com
 * Generated by: OpenAPI Generator (https://openapi-generator.tech)
 */

package openapi
// CisOrgSetting struct for CisOrgSetting
type CisOrgSetting struct {
	// true or false - Boolean that describes if the organisation is a CIS Contractor
	CISContractorEnabled bool `json:"CISContractorEnabled,omitempty"`
	// true or false - Boolean that describes if the organisation is a CIS SubContractor
	CISSubContractorEnabled bool `json:"CISSubContractorEnabled,omitempty"`
	// CIS Deduction rate for the organisation
	Rate int32 `json:"Rate,omitempty"`
}
