/*
 * Accounting API
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * API version: 2.2.8
 * Contact: api@xero.com
 * Generated by: OpenAPI Generator (https://openapi-generator.tech)
 */

package openapi
// ManualJournalLine struct for ManualJournalLine
type ManualJournalLine struct {
	// total for line. Debits are positive, credits are negative value
	LineAmount float64 `json:"LineAmount,omitempty"`
	// See Accounts
	AccountCode string `json:"AccountCode,omitempty"`
	// Description for journal line
	Description string `json:"Description,omitempty"`
	// The tax type from TaxRates
	TaxType string `json:"TaxType,omitempty"`
	// Optional Tracking Category – see Tracking. Any JournalLine can have a maximum of 2 <TrackingCategory> elements.
	Tracking []TrackingCategory `json:"Tracking,omitempty"`
	// The calculated tax amount based on the TaxType and LineAmount
	TaxAmount float64 `json:"TaxAmount,omitempty"`
	// is the line blank
	IsBlank bool `json:"IsBlank,omitempty"`
}
