/*
 * Accounting API
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * API version: 2.2.8
 * Contact: api@xero.com
 * Generated by: OpenAPI Generator (https://openapi-generator.tech)
 */

package openapi
// Allocation struct for Allocation
type Allocation struct {
	Invoice Invoice `json:"Invoice"`
	Overpayment Overpayment `json:"Overpayment,omitempty"`
	Prepayment Prepayment `json:"Prepayment,omitempty"`
	CreditNote CreditNote `json:"CreditNote,omitempty"`
	// the amount being applied to the invoice
	Amount float64 `json:"Amount"`
	// the date the allocation is applied YYYY-MM-DD.
	Date string `json:"Date"`
	// A string to indicate if a invoice status
	StatusAttributeString string `json:"StatusAttributeString,omitempty"`
	// Displays array of validation error messages from the API
	ValidationErrors []ValidationError `json:"ValidationErrors,omitempty"`
}
