/*
 * Accounting API
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * API version: 2.2.8
 * Contact: api@xero.com
 * Generated by: OpenAPI Generator (https://openapi-generator.tech)
 */

package openapi
// QuoteLineAmountTypes Line amounts are exclusive of tax by default if you don’t specify this element. See Line Amount Types
type QuoteLineAmountTypes string

// List of QuoteLineAmountTypes
const (
	QUOTELINEAMOUNTTYPES_EXCLUSIVE QuoteLineAmountTypes = "EXCLUSIVE"
	QUOTELINEAMOUNTTYPES_INCLUSIVE QuoteLineAmountTypes = "INCLUSIVE"
	QUOTELINEAMOUNTTYPES_NOTAX QuoteLineAmountTypes = "NOTAX"
)
