/*
 * Accounting API
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * API version: 2.2.8
 * Contact: api@xero.com
 * Generated by: OpenAPI Generator (https://openapi-generator.tech)
 */

package openapi
import (
	"time"
)
// Overpayment struct for Overpayment
type Overpayment struct {
	// See Overpayment Types
	Type string `json:"Type,omitempty"`
	Contact Contact `json:"Contact,omitempty"`
	// The date the overpayment is created YYYY-MM-DD
	Date string `json:"Date,omitempty"`
	// See Overpayment Status Codes
	Status string `json:"Status,omitempty"`
	LineAmountTypes LineAmountTypes `json:"LineAmountTypes,omitempty"`
	// See Overpayment Line Items
	LineItems []LineItem `json:"LineItems,omitempty"`
	// The subtotal of the overpayment excluding taxes
	SubTotal float64 `json:"SubTotal,omitempty"`
	// The total tax on the overpayment
	TotalTax float64 `json:"TotalTax,omitempty"`
	// The total of the overpayment (subtotal + total tax)
	Total float64 `json:"Total,omitempty"`
	// UTC timestamp of last update to the overpayment
	UpdatedDateUTC time.Time `json:"UpdatedDateUTC,omitempty"`
	CurrencyCode CurrencyCode `json:"CurrencyCode,omitempty"`
	// Xero generated unique identifier
	OverpaymentID string `json:"OverpaymentID,omitempty"`
	// The currency rate for a multicurrency overpayment. If no rate is specified, the XE.com day rate is used
	CurrencyRate float64 `json:"CurrencyRate,omitempty"`
	// The remaining credit balance on the overpayment
	RemainingCredit float64 `json:"RemainingCredit,omitempty"`
	// See Allocations
	Allocations []Allocation `json:"Allocations,omitempty"`
	// The amount of applied to an invoice
	AppliedAmount float64 `json:"AppliedAmount,omitempty"`
	// See Payments
	Payments []Payment `json:"Payments,omitempty"`
	// boolean to indicate if a overpayment has an attachment
	HasAttachments bool `json:"HasAttachments,omitempty"`
	// See Attachments
	Attachments []Attachment `json:"Attachments,omitempty"`
}
