/*
 * Accounting API
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * API version: 2.2.8
 * Contact: api@xero.com
 * Generated by: OpenAPI Generator (https://openapi-generator.tech)
 */

package openapi
import (
	"time"
)
// Organisation struct for Organisation
type Organisation struct {
	// Unique Xero identifier
	OrganisationID string `json:"OrganisationID,omitempty"`
	// Display a unique key used for Xero-to-Xero transactions
	APIKey string `json:"APIKey,omitempty"`
	// Display name of organisation shown in Xero
	Name string `json:"Name,omitempty"`
	// Organisation name shown on Reports
	LegalName string `json:"LegalName,omitempty"`
	// Boolean to describe if organisation is registered with a local tax authority i.e. true, false
	PaysTax bool `json:"PaysTax,omitempty"`
	// See Version Types
	Version string `json:"Version,omitempty"`
	// Organisation Type
	OrganisationType string `json:"OrganisationType,omitempty"`
	BaseCurrency CurrencyCode `json:"BaseCurrency,omitempty"`
	CountryCode CountryCode `json:"CountryCode,omitempty"`
	// Boolean to describe if organisation is a demo company.
	IsDemoCompany bool `json:"IsDemoCompany,omitempty"`
	// Will be set to ACTIVE if you can connect to organisation via the Xero API
	OrganisationStatus string `json:"OrganisationStatus,omitempty"`
	// Shows for New Zealand, Australian and UK organisations
	RegistrationNumber string `json:"RegistrationNumber,omitempty"`
	// Shown if set. US Only.
	EmployerIdentificationNumber string `json:"EmployerIdentificationNumber,omitempty"`
	// Shown if set. Displays in the Xero UI as Tax File Number (AU), GST Number (NZ), VAT Number (UK) and Tax ID Number (US & Global).
	TaxNumber string `json:"TaxNumber,omitempty"`
	// Calendar day e.g. 0-31
	FinancialYearEndDay int32 `json:"FinancialYearEndDay,omitempty"`
	// Calendar Month e.g. 1-12
	FinancialYearEndMonth int32 `json:"FinancialYearEndMonth,omitempty"`
	// The accounting basis used for tax returns. See Sales Tax Basis
	SalesTaxBasis string `json:"SalesTaxBasis,omitempty"`
	// The frequency with which tax returns are processed. See Sales Tax Period
	SalesTaxPeriod string `json:"SalesTaxPeriod,omitempty"`
	// The default for LineAmountTypes on sales transactions
	DefaultSalesTax string `json:"DefaultSalesTax,omitempty"`
	// The default for LineAmountTypes on purchase transactions
	DefaultPurchasesTax string `json:"DefaultPurchasesTax,omitempty"`
	// Shown if set. See lock dates
	PeriodLockDate string `json:"PeriodLockDate,omitempty"`
	// Shown if set. See lock dates
	EndOfYearLockDate string `json:"EndOfYearLockDate,omitempty"`
	// Timestamp when the organisation was created in Xero
	CreatedDateUTC time.Time `json:"CreatedDateUTC,omitempty"`
	Timezone TimeZone `json:"Timezone,omitempty"`
	// Organisation Type
	OrganisationEntityType string `json:"OrganisationEntityType,omitempty"`
	// A unique identifier for the organisation. Potential uses.
	ShortCode string `json:"ShortCode,omitempty"`
	// Organisation Classes describe which plan the Xero organisation is on (e.g. DEMO, TRIAL, PREMIUM)
	Class string `json:"Class,omitempty"`
	// BUSINESS or PARTNER. Partner edition organisations are sold exclusively through accounting partners and have restricted functionality (e.g. no access to invoicing)
	Edition string `json:"Edition,omitempty"`
	// Description of business type as defined in Organisation settings
	LineOfBusiness string `json:"LineOfBusiness,omitempty"`
	// Address details for organisation – see Addresses
	Addresses []Address `json:"Addresses,omitempty"`
	// Phones details for organisation – see Phones
	Phones []Phone `json:"Phones,omitempty"`
	// Organisation profile links for popular services such as Facebook,Twitter, GooglePlus and LinkedIn. You can also add link to your website here. Shown if Organisation settings  is updated in Xero. See ExternalLinks below
	ExternalLinks []ExternalLink `json:"ExternalLinks,omitempty"`
	PaymentTerms PaymentTerm `json:"PaymentTerms,omitempty"`
}
