/*
 * Accounting API
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * API version: 2.2.8
 * Contact: api@xero.com
 * Generated by: OpenAPI Generator (https://openapi-generator.tech)
 */

package openapi
// InvoiceReminder struct for InvoiceReminder
type InvoiceReminder struct {
	// setting for on or off
	Enabled bool `json:"Enabled,omitempty"`
}
