/*
 * Accounting API
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * API version: 2.2.8
 * Contact: api@xero.com
 * Generated by: OpenAPI Generator (https://openapi-generator.tech)
 */

package openapi
// Error struct for Error
type Error struct {
	// Exception number
	ErrorNumber int32 `json:"ErrorNumber,omitempty"`
	// Exception type
	Type string `json:"Type,omitempty"`
	// Exception message
	Message string `json:"Message,omitempty"`
	// Array of Elements of validation Errors
	Elements []Element `json:"Elements,omitempty"`
}
