/*
 * Accounting API
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * API version: 2.2.8
 * Contact: api@xero.com
 * Generated by: OpenAPI Generator (https://openapi-generator.tech)
 */

package openapi
import (
	"time"
)
// HistoryRecord struct for HistoryRecord
type HistoryRecord struct {
	// details
	Details string `json:"Details,omitempty"`
	// Name of branding theme
	Changes string `json:"Changes,omitempty"`
	// has a value of 0
	User string `json:"User,omitempty"`
	// UTC timestamp of creation date of branding theme
	DateUTC time.Time `json:"DateUTC,omitempty"`
}
