/*
 * Accounting API
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * API version: 2.2.8
 * Contact: api@xero.com
 * Generated by: OpenAPI Generator (https://openapi-generator.tech)
 */

package openapi
import (
	"time"
)
// Prepayment struct for Prepayment
type Prepayment struct {
	// See Prepayment Types
	Type string `json:"Type,omitempty"`
	Contact Contact `json:"Contact,omitempty"`
	// The date the prepayment is created YYYY-MM-DD
	Date string `json:"Date,omitempty"`
	// See Prepayment Status Codes
	Status string `json:"Status,omitempty"`
	LineAmountTypes LineAmountTypes `json:"LineAmountTypes,omitempty"`
	// See Prepayment Line Items
	LineItems []LineItem `json:"LineItems,omitempty"`
	// The subtotal of the prepayment excluding taxes
	SubTotal float64 `json:"SubTotal,omitempty"`
	// The total tax on the prepayment
	TotalTax float64 `json:"TotalTax,omitempty"`
	// The total of the prepayment(subtotal + total tax)
	Total float64 `json:"Total,omitempty"`
	// Returns Invoice number field. Reference field isn't available.
	Reference string `json:"Reference,omitempty"`
	// UTC timestamp of last update to the prepayment
	UpdatedDateUTC time.Time `json:"UpdatedDateUTC,omitempty"`
	CurrencyCode CurrencyCode `json:"CurrencyCode,omitempty"`
	// Xero generated unique identifier
	PrepaymentID string `json:"PrepaymentID,omitempty"`
	// The currency rate for a multicurrency prepayment. If no rate is specified, the XE.com day rate is used
	CurrencyRate float64 `json:"CurrencyRate,omitempty"`
	// The remaining credit balance on the prepayment
	RemainingCredit float64 `json:"RemainingCredit,omitempty"`
	// See Allocations
	Allocations []Allocation `json:"Allocations,omitempty"`
	// The amount of applied to an invoice
	AppliedAmount float64 `json:"AppliedAmount,omitempty"`
	// boolean to indicate if a prepayment has an attachment
	HasAttachments bool `json:"HasAttachments,omitempty"`
	// See Attachments
	Attachments []Attachment `json:"Attachments,omitempty"`
}
