/*
 * Accounting API
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * API version: 2.2.8
 * Contact: api@xero.com
 * Generated by: OpenAPI Generator (https://openapi-generator.tech)
 */

package openapi
import (
	"time"
)
// Contact struct for Contact
type Contact struct {
	// Xero identifier
	ContactID string `json:"ContactID,omitempty"`
	// This can be updated via the API only i.e. This field is read only on the Xero contact screen, used to identify contacts in external systems (max length = 50). If the Contact Number is used, this is displayed as Contact Code in the Contacts UI in Xero.
	ContactNumber string `json:"ContactNumber,omitempty"`
	// A user defined account number. This can be updated via the API and the Xero UI (max length = 50)
	AccountNumber string `json:"AccountNumber,omitempty"`
	// Current status of a contact – see contact status types
	ContactStatus string `json:"ContactStatus,omitempty"`
	// Full name of contact/organisation (max length = 255)
	Name string `json:"Name,omitempty"`
	// First name of contact person (max length = 255)
	FirstName string `json:"FirstName,omitempty"`
	// Last name of contact person (max length = 255)
	LastName string `json:"LastName,omitempty"`
	// Email address of contact person (umlauts not supported) (max length  = 255)
	EmailAddress string `json:"EmailAddress,omitempty"`
	// Skype user name of contact
	SkypeUserName string `json:"SkypeUserName,omitempty"`
	// See contact persons
	ContactPersons []ContactPerson `json:"ContactPersons,omitempty"`
	// Bank account number of contact
	BankAccountDetails string `json:"BankAccountDetails,omitempty"`
	// Tax number of contact – this is also known as the ABN (Australia), GST Number (New Zealand), VAT Number (UK) or Tax ID Number (US and global) in the Xero UI depending on which regionalized version of Xero you are using (max length = 50)
	TaxNumber string `json:"TaxNumber,omitempty"`
	// The tax type from TaxRates
	AccountsReceivableTaxType string `json:"AccountsReceivableTaxType,omitempty"`
	// The tax type from TaxRates
	AccountsPayableTaxType string `json:"AccountsPayableTaxType,omitempty"`
	// Store certain address types for a contact – see address types
	Addresses []Address `json:"Addresses,omitempty"`
	// Store certain phone types for a contact – see phone types
	Phones []Phone `json:"Phones,omitempty"`
	// true or false – Boolean that describes if a contact that has any AP  invoices entered against them. Cannot be set via PUT or POST – it is automatically set when an accounts payable invoice is generated against this contact.
	IsSupplier bool `json:"IsSupplier,omitempty"`
	// true or false – Boolean that describes if a contact has any AR invoices entered against them. Cannot be set via PUT or POST – it is automatically set when an accounts receivable invoice is generated against this contact.
	IsCustomer bool `json:"IsCustomer,omitempty"`
	DefaultCurrency CurrencyCode `json:"DefaultCurrency,omitempty"`
	// Store XeroNetworkKey for contacts.
	XeroNetworkKey string `json:"XeroNetworkKey,omitempty"`
	// The default sales account code for contacts
	SalesDefaultAccountCode string `json:"SalesDefaultAccountCode,omitempty"`
	// The default purchases account code for contacts
	PurchasesDefaultAccountCode string `json:"PurchasesDefaultAccountCode,omitempty"`
	// The default sales tracking categories for contacts
	SalesTrackingCategories []SalesTrackingCategory `json:"SalesTrackingCategories,omitempty"`
	// The default purchases tracking categories for contacts
	PurchasesTrackingCategories []SalesTrackingCategory `json:"PurchasesTrackingCategories,omitempty"`
	// The name of the Tracking Category assigned to the contact under SalesTrackingCategories and PurchasesTrackingCategories
	TrackingCategoryName string `json:"TrackingCategoryName,omitempty"`
	// The name of the Tracking Option assigned to the contact under SalesTrackingCategories and PurchasesTrackingCategories
	TrackingCategoryOption string `json:"TrackingCategoryOption,omitempty"`
	PaymentTerms PaymentTerm `json:"PaymentTerms,omitempty"`
	// UTC timestamp of last update to contact
	UpdatedDateUTC time.Time `json:"UpdatedDateUTC,omitempty"`
	// Displays which contact groups a contact is included in
	ContactGroups []ContactGroup `json:"ContactGroups,omitempty"`
	// Website address for contact (read only)
	Website string `json:"Website,omitempty"`
	BrandingTheme BrandingTheme `json:"BrandingTheme,omitempty"`
	BatchPayments BatchPaymentDetails `json:"BatchPayments,omitempty"`
	// The default discount rate for the contact (read only)
	Discount float64 `json:"Discount,omitempty"`
	Balances Balances `json:"Balances,omitempty"`
	// Displays array of attachments from the API
	Attachments []Attachment `json:"Attachments,omitempty"`
	// A boolean to indicate if a contact has an attachment
	HasAttachments bool `json:"HasAttachments,omitempty"`
	// Displays validation errors returned from the API
	ValidationErrors []ValidationError `json:"ValidationErrors,omitempty"`
	// A boolean to indicate if a contact has an validation errors
	HasValidationErrors bool `json:"HasValidationErrors,omitempty"`
	// Status of object
	StatusAttributeString string `json:"StatusAttributeString,omitempty"`
}
