/*
 * Accounting API
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * API version: 2.2.8
 * Contact: api@xero.com
 * Generated by: OpenAPI Generator (https://openapi-generator.tech)
 */

package openapi
// LineItemTracking struct for LineItemTracking
type LineItemTracking struct {
	// The Xero identifier for a tracking category
	TrackingCategoryID string `json:"TrackingCategoryID,omitempty"`
	// The Xero identifier for a tracking category option
	TrackingOptionID string `json:"TrackingOptionID,omitempty"`
	// The name of the tracking category
	Name string `json:"Name,omitempty"`
	// See Tracking Options
	Option string `json:"Option,omitempty"`
}
