/*
 * Accounting API
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * API version: 2.2.8
 * Contact: api@xero.com
 * Generated by: OpenAPI Generator (https://openapi-generator.tech)
 */

package openapi
// TaxRate struct for TaxRate
type TaxRate struct {
	// Name of tax rate
	Name string `json:"Name,omitempty"`
	// The tax type
	TaxType string `json:"TaxType,omitempty"`
	// See TaxComponents
	TaxComponents []TaxComponent `json:"TaxComponents,omitempty"`
	// See Status Codes
	Status string `json:"Status,omitempty"`
	// See ReportTaxTypes
	ReportTaxType string `json:"ReportTaxType,omitempty"`
	// Boolean to describe if tax rate can be used for asset accounts i.e.  true,false
	CanApplyToAssets bool `json:"CanApplyToAssets,omitempty"`
	// Boolean to describe if tax rate can be used for equity accounts i.e true,false
	CanApplyToEquity bool `json:"CanApplyToEquity,omitempty"`
	// Boolean to describe if tax rate can be used for expense accounts  i.e. true,false
	CanApplyToExpenses bool `json:"CanApplyToExpenses,omitempty"`
	// Boolean to describe if tax rate can be used for liability accounts  i.e. true,false
	CanApplyToLiabilities bool `json:"CanApplyToLiabilities,omitempty"`
	// Boolean to describe if tax rate can be used for revenue accounts i.e. true,false
	CanApplyToRevenue bool `json:"CanApplyToRevenue,omitempty"`
	// Tax Rate (decimal to 4dp) e.g 12.5000
	DisplayTaxRate float64 `json:"DisplayTaxRate,omitempty"`
	// Effective Tax Rate (decimal to 4dp) e.g 12.5000
	EffectiveRate float64 `json:"EffectiveRate,omitempty"`
}
