/*
 * Accounting API
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * API version: 2.2.8
 * Contact: api@xero.com
 * Generated by: OpenAPI Generator (https://openapi-generator.tech)
 */

package openapi
// BrandingThemes struct for BrandingThemes
type BrandingThemes struct {
	BrandingThemes []BrandingTheme `json:"BrandingThemes,omitempty"`
}
