/*
 * Accounting API
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * API version: 2.2.8
 * Contact: api@xero.com
 * Generated by: OpenAPI Generator (https://openapi-generator.tech)
 */

package openapi
// Element struct for Element
type Element struct {
	// Array of Validation Error message
	ValidationErrors []ValidationError `json:"ValidationErrors,omitempty"`
	// Unique ID for batch payment object with validation error
	BatchPaymentID string `json:"BatchPaymentID,omitempty"`
	BankTransactionID string `json:"BankTransactionID,omitempty"`
	CreditNoteID string `json:"CreditNoteID,omitempty"`
	ContactID string `json:"ContactID,omitempty"`
	InvoiceID string `json:"InvoiceID,omitempty"`
	ItemID string `json:"ItemID,omitempty"`
	PurchaseOrderID string `json:"PurchaseOrderID,omitempty"`
}
