/*
 * Accounting API
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * API version: 2.2.8
 * Contact: api@xero.com
 * Generated by: OpenAPI Generator (https://openapi-generator.tech)
 */

package openapi
// CisSetting struct for CisSetting
type CisSetting struct {
	// Boolean that describes if the contact is a CIS Subcontractor
	CISEnabled bool `json:"CISEnabled,omitempty"`
	// CIS Deduction rate for the contact if he is a subcontractor. If the contact is not CISEnabled, then the rate is not returned
	Rate int32 `json:"Rate,omitempty"`
}
