/*
 * Accounting API
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * API version: 2.2.8
 * Contact: api@xero.com
 * Generated by: OpenAPI Generator (https://openapi-generator.tech)
 */

package openapi
// PaymentService struct for PaymentService
type PaymentService struct {
	// Xero identifier
	PaymentServiceID string `json:"PaymentServiceID,omitempty"`
	// Name of payment service
	PaymentServiceName string `json:"PaymentServiceName,omitempty"`
	// The custom payment URL
	PaymentServiceUrl string `json:"PaymentServiceUrl,omitempty"`
	// The text displayed on the Pay Now button in Xero Online Invoicing. If this is not set it will default to Pay by credit card
	PayNowText string `json:"PayNowText,omitempty"`
	// This will always be CUSTOM for payment services created via the API.
	PaymentServiceType string `json:"PaymentServiceType,omitempty"`
	// Displays array of validation error messages from the API
	ValidationErrors []ValidationError `json:"ValidationErrors,omitempty"`
}
