/*
 * Accounting API
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * API version: 2.2.8
 * Contact: api@xero.com
 * Generated by: OpenAPI Generator (https://openapi-generator.tech)
 */

package openapi
import (
	"time"
)
// BankTransaction struct for BankTransaction
type BankTransaction struct {
	// See Bank Transaction Types
	Type string `json:"Type"`
	Contact Contact `json:"Contact"`
	// See LineItems
	LineItems []LineItem `json:"LineItems"`
	BankAccount Account `json:"BankAccount"`
	// Boolean to show if transaction is reconciled
	IsReconciled bool `json:"IsReconciled,omitempty"`
	// Date of transaction – YYYY-MM-DD
	Date string `json:"Date,omitempty"`
	// Reference for the transaction. Only supported for SPEND and RECEIVE transactions.
	Reference string `json:"Reference,omitempty"`
	CurrencyCode CurrencyCode `json:"CurrencyCode,omitempty"`
	// Exchange rate to base currency when money is spent or received. e.g.0.7500 Only used for bank transactions in non base currency. If this isn’t specified for non base currency accounts then either the user-defined rate (preference) or the XE.com day rate will be used. Setting currency is only supported on overpayments.
	CurrencyRate float64 `json:"CurrencyRate,omitempty"`
	// URL link to a source document – shown as “Go to App Name”
	Url string `json:"Url,omitempty"`
	// See Bank Transaction Status Codes
	Status string `json:"Status,omitempty"`
	LineAmountTypes LineAmountTypes `json:"LineAmountTypes,omitempty"`
	// Total of bank transaction excluding taxes
	SubTotal float64 `json:"SubTotal,omitempty"`
	// Total tax on bank transaction
	TotalTax float64 `json:"TotalTax,omitempty"`
	// Total of bank transaction tax inclusive
	Total float64 `json:"Total,omitempty"`
	// Xero generated unique identifier for bank transaction
	BankTransactionID string `json:"BankTransactionID,omitempty"`
	// Xero generated unique identifier for a Prepayment. This will be returned on BankTransactions with a Type of SPEND-PREPAYMENT or RECEIVE-PREPAYMENT
	PrepaymentID string `json:"PrepaymentID,omitempty"`
	// Xero generated unique identifier for an Overpayment. This will be returned on BankTransactions with a Type of SPEND-OVERPAYMENT or RECEIVE-OVERPAYMENT
	OverpaymentID string `json:"OverpaymentID,omitempty"`
	// Last modified date UTC format
	UpdatedDateUTC time.Time `json:"UpdatedDateUTC,omitempty"`
	// Boolean to indicate if a bank transaction has an attachment
	HasAttachments bool `json:"HasAttachments,omitempty"`
	// A string to indicate if a invoice status
	StatusAttributeString string `json:"StatusAttributeString,omitempty"`
	// Displays array of validation error messages from the API
	ValidationErrors []ValidationError `json:"ValidationErrors,omitempty"`
}
