/*
 * Accounting API
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * API version: 2.2.8
 * Contact: api@xero.com
 * Generated by: OpenAPI Generator (https://openapi-generator.tech)
 */

package openapi
import (
	"time"
)
// ManualJournal struct for ManualJournal
type ManualJournal struct {
	// Description of journal being posted
	Narration string `json:"Narration"`
	// See JournalLines
	JournalLines []ManualJournalLine `json:"JournalLines,omitempty"`
	// Date journal was posted – YYYY-MM-DD
	Date string `json:"Date,omitempty"`
	LineAmountTypes LineAmountTypes `json:"LineAmountTypes,omitempty"`
	// See Manual Journal Status Codes
	Status string `json:"Status,omitempty"`
	// Url link to a source document – shown as “Go to [appName]” in the Xero app
	Url string `json:"Url,omitempty"`
	// Boolean – default is true if not specified
	ShowOnCashBasisReports bool `json:"ShowOnCashBasisReports,omitempty"`
	// Boolean to indicate if a manual journal has an attachment
	HasAttachments bool `json:"HasAttachments,omitempty"`
	// Last modified date UTC format
	UpdatedDateUTC time.Time `json:"UpdatedDateUTC,omitempty"`
	// The Xero identifier for a Manual Journal
	ManualJournalID string `json:"ManualJournalID,omitempty"`
	// A string to indicate if a invoice status
	StatusAttributeString string `json:"StatusAttributeString,omitempty"`
	// Displays array of warning messages from the API
	Warnings []ValidationError `json:"Warnings,omitempty"`
	// Displays array of validation error messages from the API
	ValidationErrors []ValidationError `json:"ValidationErrors,omitempty"`
	// Displays array of attachments from the API
	Attachments []Attachment `json:"Attachments,omitempty"`
}
