/*
 * Accounting API
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * API version: 2.2.8
 * Contact: api@xero.com
 * Generated by: OpenAPI Generator (https://openapi-generator.tech)
 */

package openapi
import (
	"time"
)
// ReportWithRow struct for ReportWithRow
type ReportWithRow struct {
	// Report id
	ReportID string `json:"ReportID,omitempty"`
	// Name of the report
	ReportName string `json:"ReportName,omitempty"`
	// Title of the report
	ReportTitle string `json:"ReportTitle,omitempty"`
	// The type of report (BalanceSheet,ProfitLoss, etc)
	ReportType string `json:"ReportType,omitempty"`
	// Report titles array (3 to 4 strings with the report name, orgnisation name and time frame of report)
	ReportTitles []string `json:"ReportTitles,omitempty"`
	// Date of report
	ReportDate string `json:"ReportDate,omitempty"`
	Rows []ReportRows `json:"Rows,omitempty"`
	// Updated Date
	UpdatedDateUTC time.Time `json:"UpdatedDateUTC,omitempty"`
	Fields []ReportFields `json:"Fields,omitempty"`
}
