/*
 * Accounting API
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * API version: 2.2.8
 * Contact: api@xero.com
 * Generated by: OpenAPI Generator (https://openapi-generator.tech)
 */

package openapi
// SalesTrackingCategory struct for SalesTrackingCategory
type SalesTrackingCategory struct {
	// The default sales tracking category name for contacts
	TrackingCategoryName string `json:"TrackingCategoryName,omitempty"`
	// The default purchase tracking category name for contacts
	TrackingOptionName string `json:"TrackingOptionName,omitempty"`
}
