/*
 * Accounting API
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * API version: 2.2.8
 * Contact: api@xero.com
 * Generated by: OpenAPI Generator (https://openapi-generator.tech)
 */

package openapi
// ReportCell struct for ReportCell
type ReportCell struct {
	Value string `json:"Value,omitempty"`
	Attributes []ReportAttribute `json:"Attributes,omitempty"`
}
