/*
 * Accounting API
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * API version: 2.2.8
 * Contact: api@xero.com
 * Generated by: OpenAPI Generator (https://openapi-generator.tech)
 */

package openapi
// Bill struct for Bill
type Bill struct {
	// Day of Month (0-31)
	Day int32 `json:"Day,omitempty"`
	Type PaymentTermType `json:"Type,omitempty"`
}
