/*
 * Accounting API
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * API version: 2.2.8
 * Contact: api@xero.com
 * Generated by: OpenAPI Generator (https://openapi-generator.tech)
 */

package openapi
import (
	"time"
)
// User struct for User
type User struct {
	// Xero identifier
	UserID string `json:"UserID,omitempty"`
	// Email address of user
	EmailAddress string `json:"EmailAddress,omitempty"`
	// First name of user
	FirstName string `json:"FirstName,omitempty"`
	// Last name of user
	LastName string `json:"LastName,omitempty"`
	// Timestamp of last change to user
	UpdatedDateUTC time.Time `json:"UpdatedDateUTC,omitempty"`
	// Boolean to indicate if user is the subscriber
	IsSubscriber bool `json:"IsSubscriber,omitempty"`
	// User role that defines permissions in Xero and via API (READONLY, INVOICEONLY, STANDARD, FINANCIALADVISER, etc)
	OrganisationRole string `json:"OrganisationRole,omitempty"`
}
