/*
 * Accounting API
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * API version: 2.2.8
 * Contact: api@xero.com
 * Generated by: OpenAPI Generator (https://openapi-generator.tech)
 */

package openapi
import (
	"time"
)
// Report struct for Report
type Report struct {
	// See Prepayment Types
	ReportID string `json:"ReportID,omitempty"`
	// See Prepayment Types
	ReportName string `json:"ReportName,omitempty"`
	// See Prepayment Types
	ReportType string `json:"ReportType,omitempty"`
	// See Prepayment Types
	ReportTitle string `json:"ReportTitle,omitempty"`
	// Date of report
	ReportDate string `json:"ReportDate,omitempty"`
	// Updated Date
	UpdatedDateUTC time.Time `json:"UpdatedDateUTC,omitempty"`
	Contacts []TenNinteyNineContact `json:"Contacts,omitempty"`
}
